server:
  port: 5000
---
environment: production
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 7070
---
environment: testing
spring:
  config:
    activate:
      on-profile: test
server:
  port: 4000
  

  

